### ISSUE TITLE
Android Studio and react native bundler method conflicts

### ISSUE THREAD

**Issue by iamchathu** [brodybits/create-react-native-module#108] opened 2019-09-10 11:22 UTC
I have added more information about the question in [Stackoverflow](https://stackoverflow.com/questions/57834464/react-native-android-module-conflicting-with-andorid-studio-and-react-native-bui)

**Comment by iamchathu** [comment] 2019-09-11 04:09
Seems you are not using `node-modules` react native version inside the generated Android project.

**Comment by brodybits** [comment] 2019-09-11 17:51
> I have added more information about the question in [Stackoverflow](https://stackoverflow.com/questions/57834464/react-native-android-module-conflicting-with-andorid-studio-and-react-native-bui)

I just upvoted the question and existing answer. I cannot promise when I will get a chance to parse what may be going on and try to reproduce the issue.

> Seems you are not using `node-modules` react native version inside the generated Android project.

Can you or someone else explain this in some easier terms?

Help from the user community would be much appreciated.

**Comment by brodybits** [comment] 2019-09-13 17:26
Is this covered by #120 or is it something different?

**Comment by brodybits** [comment] 2019-09-19 14:51
I am closing this since I really do not follow what is going on and have not seen response to my followup questions.

**Closed by brodybits** 2019-09-19 14:51 UTC
Labels: help wanted, info-needed

**Comment by iamchathu** [comment] 2019-09-20 03:42
@brodybits For now I generated new project and migrated my old project to new version and it's works now.

**Comment by brodybits** [comment] 2019-09-20 20:13
Thanks for the confirmation.
